name: duma_health
description: duma health an app for requesting a doctor appointment

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.6
  flutter_font_icons: ^2.2.4
  animated_splash_screen: ^1.0.1+2
  google_fonts: ^3.0.1
  intl: ^0.17.0
  dio: ^4.0.4
  go_router: ^6.0.9
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.5
  webview_flutter: ^2.0.13
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4
  fluttertoast: ^8.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/